# Generated by Django 5.0.1 on 2024-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_rename_assigent_to_ticket_assiged_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assiged_to',
            new_name='assigned_to',
        ),
    ]
